//! Regenerates the committed artifacts under `assets/`.
//!
//! ```sh
//! cargo run -- write   # regenerate
//! cargo run -- check   # fail if what is committed is stale
//! ```
//!
//! # Why commit generated files at all
//!
//! Because a diff is the cheapest review there is, and this repository's
//! recurring defect is a change whose consequences nobody saw.
//!
//! The schema is declared in Rust (`G2.7`) and each dialect renders it. Nothing
//! in a pull request shows what the *SQL* became — a reviewer would have to run
//! six commands to find out, and reviewers do not. With the DDL committed, a
//! type mapping that changes shows up as a changed `.sql` file, and a dialect
//! that becomes a copy of another shows up as **two identical files**.
//!
//! That last property is the point. `openehr-mariadb` shipped as a
//! name-substituted copy of `openehr-mysql` and the only thing that would have
//! revealed it at review time was seeing the two scripts side by side
//! (`spec/audit.md` **W-01**).
//!
//! # `check` is the half that matters
//!
//! Regeneration nobody verifies is regeneration that stops happening. `check`
//! re-renders everything, compares it against what is committed, and fails
//! naming the stale file — so a schema change that forgets to update `assets/`
//! fails CI rather than leaving a lie in the tree.

use openehr_store::{ColTy, Dialect, TABLES, ddl_script};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Every dialect, in the order their files are written.
fn dialects() -> Vec<(&'static str, &'static dyn Dialect)> {
    vec![
        ("postgresql", &openehr_postgresql::PostgresqlDialect),
        ("sqlite", &openehr_sqlite::SqliteDialect),
        ("mysql", &openehr_mysql::MysqlDialect),
        ("mariadb", &openehr_mariadb::MariadbDialect),
        ("mssql", &openehr_mssql::MssqlDialect),
        ("oracle", &openehr_oracle::OracleDialect),
    ]
}

/// Every logical column type, so the matrix covers all of them.
///
/// Listed rather than iterated because `ColTy` is deliberately not an
/// enumerable set (`M3.30`); adding a variant should break this, loudly, in the
/// same way it breaks every dialect.
fn column_types() -> Vec<(&'static str, ColTy)> {
    vec![
        ("Id(255)", ColTy::Id(255)),
        ("Text(255)", ColTy::Text(255)),
        ("LongText", ColTy::LongText),
        ("Json", ColTy::Json),
        ("Instant", ColTy::Instant),
        ("InstantUtc", ColTy::InstantUtc),
        ("Int", ColTy::Int),
        ("Bool", ColTy::Bool),
    ]
}

/// One artifact: where it goes and what it should contain.
struct Asset {
    path: PathBuf,
    body: String,
}

fn header(what: &str) -> String {
    format!(
        "-- {what}\n\
         --\n\
         -- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`\n\
         -- in openehr-assets/ and commit the diff.\n\
         --\n\
         -- Committed so that a change to the schema or to a dialect is visible\n\
         -- as a diff at review time, and so that two dialects becoming the same\n\
         -- thing shows up as two identical files (spec/audit.md W-01).\n\n"
    )
}

fn build(root: &Path) -> Vec<Asset> {
    let mut assets = Vec::new();

    // The shared schema, as data. `schema.rs` derives `Serialize` for exactly
    // this: a tool that dumps it for inspection. Nothing reads it back — a
    // schema read from JSON would be a second source of truth.
    let schema = serde_json::to_string_pretty(&TABLES).expect("schema serializes");
    assets.push(Asset {
        path: root.join("assets/schema.json"),
        body: format!("{schema}\n"),
    });

    // One DDL script per engine.
    for (name, dialect) in dialects() {
        assets.push(Asset {
            path: root.join(format!("assets/ddl/{name}.sql")),
            body: format!(
                "{}{}",
                header(&format!("openEHR schema for {}", dialect.name())),
                ddl_script(dialect)
            ),
        });
    }

    // The type matrix, side by side. A reviewer reading one column against
    // another is the cheapest available check that a dialect is its own engine
    // (`X15.19`).
    let mut matrix = String::new();
    matrix.push_str(
        "# Column type matrix\n\n\
         GENERATED by `openehr-assets`. Do not edit.\n\n\
         Every logical column type, as each engine spells it. Two identical\n\
         columns below mean two dialects agree on every type — which is legal\n\
         (MySQL and MariaDB do) but is also what a copied dialect looks like, so\n\
         it should be a deliberate, documented agreement and not a surprise.\n\n",
    );
    let _ = write!(matrix, "| `ColTy` |");
    for (name, _) in dialects() {
        let _ = write!(matrix, " {name} |");
    }
    matrix.push_str("\n| --- |");
    for _ in dialects() {
        matrix.push_str(" --- |");
    }
    matrix.push('\n');
    for (label, ty) in column_types() {
        let _ = write!(matrix, "| `{label}` |");
        for (_, dialect) in dialects() {
            let _ = write!(matrix, " `{}` |", dialect.col_sql(ty));
        }
        matrix.push('\n');
    }
    let _ = write!(matrix, "\n| Property |");
    for (name, _) in dialects() {
        let _ = write!(matrix, " {name} |");
    }
    matrix.push_str("\n| --- |");
    for _ in dialects() {
        matrix.push_str(" --- |");
    }
    let _ = write!(matrix, "\n| placeholder |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{}` |", dialect.placeholder().render(1));
    }
    let _ = write!(matrix, "\n| quoting |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{}` |", dialect.quote("x"));
    }
    let _ = write!(matrix, "\n| table idempotence |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{:?}` |", dialect.table_idempotence());
    }
    let _ = write!(matrix, "\n| index idempotence |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{:?}` |", dialect.index_idempotence());
    }
    matrix.push('\n');
    assets.push(Asset {
        path: root.join("assets/column-type-matrix.md"),
        body: matrix,
    });

    assets.push(invariant_coverage(root));
    assets
}

/// Every `(class, invariant)` pair the crate reports in a `ParseError`.
///
/// Hand-rolled rather than a regex crate: the shape is fixed and adding a
/// dependency to a repository tool to match one literal would be the wrong
/// trade.
fn regex_citations(source: &str) -> Vec<(String, String)> {
    // Two reporting forms, and missing one of them makes the report lie by
    // omission. `ParseError::invariant` is the construction path;
    // `ctx.violation` is the validation path, which is where most invariants
    // are actually reported. Scanning only the first hid every divergence in
    // `validation.rs` until a test failure surfaced it.
    let mut out = Vec::new();
    let sites = source
        .match_indices("ParseError::invariant(")
        .chain(source.match_indices(".violation("));
    for (index, _) in sites {
        let tail = &source[index..];
        let quoted: Vec<&str> = tail
            .split('"')
            .skip(1)
            .step_by(2)
            .take(2)
            .collect();
        if quoted.len() == 2
            && quoted[0].chars().all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit())
            && !quoted[1].is_empty()
            // Identifier-shaped only. A `ParseError::invariant` call whose
            // second argument is a sentence is a detail message, not a name.
            && quoted[1]
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_')
        {
            out.push((quoted[0].to_owned(), quoted[1].to_owned()));
        }
    }
    out.sort();
    out.dedup();
    out
}

/// Reports which openEHR RM invariants the `openehr` crate **names**.
///
/// # What this measures, and what it does not
///
/// It greps the crate's source for each invariant's name. That is weak evidence
/// and is labelled as such: a name present means somebody wrote the rule down
/// next to code, not that the code enforces it, and a name absent means only
/// that this crude test did not find it.
///
/// It is still worth having. Before this existed, "which RM invariants does the
/// crate enforce?" had no answer at all, and the two that turned out to be
/// neither enforced nor declared (`lib:A-19`, `COMPOSITION.Territory_valid` and
/// `Language_valid`) were invisible. A weak measure that is honest about being
/// weak beats no measure, provided nobody promotes it to a conformance claim —
/// which `C0.20` forbids.
///
/// The invariants come from `assets/rm-1.1.0-invariants.json`, distilled from
/// the openEHR BMM. The BMM carries the **expressions**, not merely the names,
/// which is what made this checkable at all.
fn invariant_coverage(root: &Path) -> Asset {
    let raw = std::fs::read_to_string(root.join("assets/rm-1.1.0-invariants.json"))
        .expect("assets/rm-1.1.0-invariants.json is committed");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("invariants parse");
    let classes: BTreeMap<String, BTreeMap<String, String>> =
        serde_json::from_value(doc["classes"].clone()).expect("classes parse");

    // Read every Rust source file in the library.
    let mut source = String::new();
    let mut stack = vec![root.join("openehr/src")];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("read openehr/src").flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "rs") {
                source.push_str(&std::fs::read_to_string(&path).expect("read source"));
                source.push('\n');
            }
        }
    }

    // `lib:L10.4` requires the crate to report openEHR's *own* invariant names,
    // so a reader can find the rule in the class definition. A prior audit
    // found five violations by hand and said "and three more" without naming
    // them. This finds them all, every time it runs.
    let cited = regex_citations(&source);
    let mut divergent: Vec<(String, String, Vec<String>)> = Vec::new();
    for (class, ours) in &cited {
        if let Some(theirs) = classes.get(class)
            && !theirs.contains_key(ours)
        {
            divergent.push((class.clone(), ours.clone(), theirs.keys().cloned().collect()));
        }
    }
    divergent.sort();

    let mut named = 0usize;
    let mut unnamed: Vec<(String, String)> = Vec::new();
    for (class, invariants) in &classes {
        for name in invariants.keys() {
            // The BMM has stray spaces in a few names ("Lifecycle_state_ valid").
            let squashed = name.replace(' ', "");
            let underscored = name.replace(' ', "_");
            if source.contains(name.as_str())
                || source.contains(&squashed)
                || source.contains(&underscored)
            {
                named += 1;
            } else {
                unnamed.push((class.clone(), name.clone()));
            }
        }
    }
    let total = named + unnamed.len();

    let mut body = String::new();
    body.push_str(
        "# RM invariant coverage\n\n\
         GENERATED by `openehr-assets`. Do not edit.\n\n\
         ## What this is\n\n\
         Every invariant openEHR RM 1.1.0 declares, against whether the `openehr`\n\
         crate's source **names** it.\n\n\
         **Naming is not enforcing.** This is a grep. A name present means the\n\
         rule was written down beside code; a name absent means only that this\n\
         crude test did not find it. It MUST NOT be promoted to a conformance\n\
         claim (`db:C0.20`) — the [conformance matrix](../spec/databases/conformance-matrix.md)\n\
         is where verified status lives.\n\n\
         It is still worth having: before it existed, the question had no answer,\n\
         and the two invariants that turned out to be neither enforced nor\n\
         declared were invisible (`lib:A-19`).\n\n\
         Source: the openEHR BMM, which carries invariant **expressions** and not\n\
         merely names — see `rm-1.1.0-invariants.json`.\n\n",
    );
    let _ = writeln!(body, "## Summary\n");
    let _ = writeln!(body, "| | Count |");
    let _ = writeln!(body, "| --- | --- |");
    let _ = writeln!(body, "| Invariants in RM 1.1.0 | {total} |");
    let _ = writeln!(body, "| Named in the crate's source | {named} |");
    let _ = writeln!(body, "| Not named | {} |", unnamed.len());
    let _ = writeln!(
        body,
        "\nNot-named includes invariants that are **out of scope** by a declared \
         exclusion (EHR Extract, `lib:S1.6`; the Archetype Model, `lib:S1.4`), \
         invariants that are **vacuous in Rust** (`X /= Void implies not \
         X.is_empty` — an empty `Vec` is the absent case), and invariants that \
         are genuinely unenforced. Distinguishing those three needs a human, and \
         this file does not attempt it.\n"
    );
    // An addition is only legitimate once declared (`lib:L10.9`). Reading the
    // register out of the spec means the report cannot drift from it.
    let declared = std::fs::read_to_string(root.join("openehr/spec/10-validation.md"))
        .unwrap_or_default();
    write_divergences(&mut body, &divergent, &declared);
    let _ = writeln!(body, "## Not named in the crate's source\n");
    let _ = writeln!(body, "| Class | Invariant |");
    let _ = writeln!(body, "| --- | --- |");
    for (class, name) in &unnamed {
        let _ = writeln!(body, "| `{class}` | `{name}` |");
    }
    Asset {
        path: root.join("assets/invariant-coverage.md"),
        body,
    }
}

/// The `L10.4` section of the coverage report.
fn write_divergences(
    body: &mut String,
    divergent: &[(String, String, Vec<String>)],
    declared: &str,
) {
    let _ = writeln!(
        body,
        "## Invariant names that diverge from openEHR (`lib:L10.4`)\n"
    );
    let _ = writeln!(
        body,
        "`L10.4` requires the crate to report openEHR's own invariant names, so a reader can find the rule in the class definition. A name the specification does not contain fails that.\n\nOnly classes openEHR gives invariants to are listed; where openEHR states none, a crate rule is an addition rather than a rename.\n"
    );
    if divergent.is_empty() {
        let _ = writeln!(body, "None.\n");
    } else {
        let _ = writeln!(
            body,
            "| Class | Crate reports | Declared (`lib:L10.9`) | openEHR declares |"
        );
        let _ = writeln!(body, "| --- | --- | --- | --- |");
        for (class, ours, theirs) in divergent {
            let mark = if declared.contains(&format!("| `{ours}` |")) {
                "yes"
            } else {
                "**NO**"
            };
            let _ = writeln!(
                body,
                "| `{class}` | `{ours}` | {mark} | {} |",
                theirs
                    .iter()
                    .map(|t| format!("`{t}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let _ = writeln!(body);
    }

}

fn main() -> std::process::ExitCode {
    let mode = std::env::args().nth(1).unwrap_or_else(|| "write".to_owned());
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repository root")
        .to_path_buf();
    let assets = build(&root);

    match mode.as_str() {
        "write" => {
            for asset in &assets {
                if let Some(parent) = asset.path.parent() {
                    std::fs::create_dir_all(parent).expect("create assets directory");
                }
                std::fs::write(&asset.path, &asset.body).expect("write asset");
                println!("wrote {}", asset.path.display());
            }
            std::process::ExitCode::SUCCESS
        }
        "check" => {
            let mut stale = Vec::new();
            for asset in &assets {
                let current = std::fs::read_to_string(&asset.path).unwrap_or_default();
                if current != asset.body {
                    stale.push(asset.path.display().to_string());
                }
            }
            if stale.is_empty() {
                println!("assets are current ({} files)", assets.len());
                std::process::ExitCode::SUCCESS
            } else {
                eprintln!("stale assets — run `cargo run -- write` in openehr-assets/:");
                for path in &stale {
                    eprintln!("  {path}");
                }
                std::process::ExitCode::FAILURE
            }
        }
        other => {
            eprintln!("usage: openehr-assets [write|check]  (got {other:?})");
            std::process::ExitCode::FAILURE
        }
    }
}
