//! Regenerates the committed artifacts under `assets/`.
//!
//! ```sh
//! cargo run -- write   # regenerate
//! cargo run -- check   # fail if what is committed is stale
//! ```
//!
//! # Why commit generated files at all
//!
//! Because a diff is the cheapest review there is, and this repository's
//! recurring defect is a change whose consequences nobody saw.
//!
//! The schema is declared in Rust (`G2.7`) and each dialect renders it. Nothing
//! in a pull request shows what the *SQL* became — a reviewer would have to run
//! six commands to find out, and reviewers do not. With the DDL committed, a
//! type mapping that changes shows up as a changed `.sql` file, and a dialect
//! that becomes a copy of another shows up as **two identical files**.
//!
//! That last property is the point. `openehr-mariadb` shipped as a
//! name-substituted copy of `openehr-mysql` and the only thing that would have
//! revealed it at review time was seeing the two scripts side by side
//! (`spec/audit.md` **W-01**).
//!
//! # `check` is the half that matters
//!
//! Regeneration nobody verifies is regeneration that stops happening. `check`
//! re-renders everything, compares it against what is committed, and fails
//! naming the stale file — so a schema change that forgets to update `assets/`
//! fails CI rather than leaving a lie in the tree.

use openehr_store::{ColTy, Dialect, TABLES, ddl_script};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Every dialect, in the order their files are written.
fn dialects() -> Vec<(&'static str, &'static dyn Dialect)> {
    vec![
        ("postgresql", &openehr_postgresql::PostgresqlDialect),
        ("sqlite", &openehr_sqlite::SqliteDialect),
        ("mysql", &openehr_mysql::MysqlDialect),
        ("mariadb", &openehr_mariadb::MariadbDialect),
        ("mssql", &openehr_mssql::MssqlDialect),
        ("oracle", &openehr_oracle::OracleDialect),
    ]
}

/// Every logical column type, so the matrix covers all of them.
///
/// Listed rather than iterated because `ColTy` is deliberately not an
/// enumerable set (`M3.30`); adding a variant should break this, loudly, in the
/// same way it breaks every dialect.
fn column_types() -> Vec<(&'static str, ColTy)> {
    vec![
        ("Id(255)", ColTy::Id(255)),
        ("Text(255)", ColTy::Text(255)),
        ("LongText", ColTy::LongText),
        ("Json", ColTy::Json),
        ("Instant", ColTy::Instant),
        ("InstantUtc", ColTy::InstantUtc),
        ("Int", ColTy::Int),
        ("Bool", ColTy::Bool),
    ]
}

/// One artifact: where it goes and what it should contain.
struct Asset {
    path: PathBuf,
    body: String,
}

fn header(what: &str) -> String {
    format!(
        "-- {what}\n\
         --\n\
         -- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`\n\
         -- in openehr-assets/ and commit the diff.\n\
         --\n\
         -- Committed so that a change to the schema or to a dialect is visible\n\
         -- as a diff at review time, and so that two dialects becoming the same\n\
         -- thing shows up as two identical files (spec/audit.md W-01).\n\n"
    )
}

fn build(root: &Path) -> Vec<Asset> {
    let mut assets = Vec::new();

    // The shared schema, as data. `schema.rs` derives `Serialize` for exactly
    // this: a tool that dumps it for inspection. Nothing reads it back — a
    // schema read from JSON would be a second source of truth.
    let schema = serde_json::to_string_pretty(&TABLES).expect("schema serializes");
    assets.push(Asset {
        path: root.join("assets/schema.json"),
        body: format!("{schema}\n"),
    });

    // One DDL script per engine.
    for (name, dialect) in dialects() {
        assets.push(Asset {
            path: root.join(format!("assets/ddl/{name}.sql")),
            body: format!(
                "{}{}",
                header(&format!("openEHR schema for {}", dialect.name())),
                ddl_script(dialect)
            ),
        });
    }

    // The type matrix, side by side. A reviewer reading one column against
    // another is the cheapest available check that a dialect is its own engine
    // (`X15.19`).
    let mut matrix = String::new();
    matrix.push_str(
        "# Column type matrix\n\n\
         GENERATED by `openehr-assets`. Do not edit.\n\n\
         Every logical column type, as each engine spells it. Two identical\n\
         columns below mean two dialects agree on every type — which is legal\n\
         (MySQL and MariaDB do) but is also what a copied dialect looks like, so\n\
         it should be a deliberate, documented agreement and not a surprise.\n\n",
    );
    let _ = write!(matrix, "| `ColTy` |");
    for (name, _) in dialects() {
        let _ = write!(matrix, " {name} |");
    }
    matrix.push_str("\n| --- |");
    for _ in dialects() {
        matrix.push_str(" --- |");
    }
    matrix.push('\n');
    for (label, ty) in column_types() {
        let _ = write!(matrix, "| `{label}` |");
        for (_, dialect) in dialects() {
            let _ = write!(matrix, " `{}` |", dialect.col_sql(ty));
        }
        matrix.push('\n');
    }
    let _ = write!(matrix, "\n| Property |");
    for (name, _) in dialects() {
        let _ = write!(matrix, " {name} |");
    }
    matrix.push_str("\n| --- |");
    for _ in dialects() {
        matrix.push_str(" --- |");
    }
    let _ = write!(matrix, "\n| placeholder |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{}` |", dialect.placeholder().render(1));
    }
    let _ = write!(matrix, "\n| quoting |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{}` |", dialect.quote("x"));
    }
    let _ = write!(matrix, "\n| table idempotence |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{:?}` |", dialect.table_idempotence());
    }
    let _ = write!(matrix, "\n| index idempotence |");
    for (_, dialect) in dialects() {
        let _ = write!(matrix, " `{:?}` |", dialect.index_idempotence());
    }
    matrix.push('\n');
    assets.push(Asset {
        path: root.join("assets/column-type-matrix.md"),
        body: matrix,
    });

    assets.push(invariant_coverage(root));
    assets
}

/// Every `(class, invariant)` pair the crate reports in a `ParseError`.
///
/// Hand-rolled rather than a regex crate: the shape is fixed and adding a
/// dependency to a repository tool to match one literal would be the wrong
/// trade.
/// Whether a character can appear inside a Rust identifier.
///
/// Used to tell the `r` of a raw string from the `r` ending `char` or `for`.
const fn is_ident(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_'
}

/// Consumes a raw string body and its closing delimiter.
fn skip_raw_string(chars: &mut std::iter::Peekable<std::str::Chars<'_>>, hashes: usize) {
    while let Some(c) = chars.next() {
        if c != '"' {
            continue;
        }
        let mut seen = 0usize;
        while seen < hashes && chars.peek() == Some(&'#') {
            chars.next();
            seen += 1;
        }
        if seen == hashes {
            return;
        }
    }
}

fn regex_citations(source: &str) -> Vec<(String, String)> {
    // **Any** adjacent pair of string literals shaped like a class and an
    // invariant, not an enumerated list of call forms.
    //
    // This scanned for `ParseError::invariant(` and `.violation(` only. Both
    // are real reporting paths and neither is the whole set: `check_party` and
    // `check_optional_group` take the class and invariant as literals and
    // report through them, so every rule enforced by a helper was invisible.
    // `ATTESTATION.Reason_valid` and `PARTICIPATION.Function_valid` were
    // enforced all along while this file called them unenforced — a claim that
    // reached `lib:A-25`'s own text before the code was read (`W0.3`).
    //
    // An enumerated list of call forms is a guard only as wide as its list, and
    // that shape has now bitten twice in one register. Matching the *pair*
    // needs no list: a helper added tomorrow is covered.
    //
    // Comments are skipped, so a note explaining that a rule is **not** checked
    // cannot make it count as checked. That skipping is done by a scanner and
    // not by searching for `//`, because a first attempt at the latter
    // truncated `"https://…"` mid-literal and put every quote after it out of
    // phase — which silently *un*named forty rules that were fine.
    // Each literal, and the source text between it and the one before. A
    // citation's two arguments are separated by exactly a comma: that gap is
    // what tells `invariant("ELEMENT", "Inv_null_valid")` apart from any
    // uppercase literal that merely happens to precede an identifier-shaped
    // one somewhere in the file (`lib:A-31`).
    let mut literals: Vec<(String, String)> = Vec::new();
    let mut gap = String::new();
    let mut chars = source.chars().peekable();
    let mut current: Option<String> = None;
    // Raw strings are skipped whole. The library carries 39 of them, mostly
    // JSON fixtures, and a scanner that read `r#"…"#` as an ordinary literal
    // would take their inner quotes as boundaries. Today that is harmless
    // because JSON always separates two quoted tokens, so no pair of fragments
    // can look like a citation — but "harmless because of how the fixtures
    // happen to be punctuated" is not a property worth resting on, and a raw
    // string holding an *odd* number of quotes would put the rest of the file
    // out of phase, which is the bug this scanner exists to have stopped
    // having.
    let mut previous = ' ';
    #[allow(unused_assignments)]
    while let Some(c) = chars.next() {
        if current.is_none() && c == 'r' && !is_ident(previous) {
            let mut hashes = 0usize;
            while chars.peek() == Some(&'#') {
                chars.next();
                hashes += 1;
            }
            if chars.peek() == Some(&'"') {
                chars.next();
                skip_raw_string(&mut chars, hashes);
                previous = ' ';
                continue;
            }
            // `r` began an identifier after all; nothing was consumed but the
            // hashes, which cannot start a literal.
            previous = 'r';
            continue;
        }
        previous = c;
        match (&mut current, c) {
            // Inside a literal: only an unescaped quote ends it.
            (Some(buffer), '\\') => {
                buffer.push('\\');
                if let Some(escaped) = chars.next() {
                    buffer.push(escaped);
                }
            }
            (Some(_), '"') => {
                literals.push((current.take().unwrap_or_default(), std::mem::take(&mut gap)));
            }
            (Some(buffer), other) => buffer.push(other),
            // Outside: a quote opens one, and a slash may open a comment.
            (None, '"') => current = Some(String::new()),
            (None, '/') => match chars.peek() {
                Some('/') => {
                    for c in chars.by_ref() {
                        if c == '\n' {
                            break;
                        }
                    }
                }
                Some('*') => {
                    let mut last = ' ';
                    for c in chars.by_ref() {
                        if last == '*' && c == '/' {
                            break;
                        }
                        last = c;
                    }
                }
                _ => {}
            },
            (None, other) => gap.push(other),
        }
    }

    let mut out = Vec::new();
    for pair in literals.windows(2) {
        let (class, invariant) = (pair[0].0.as_str(), pair[1].0.as_str());
        // The two must be one call's arguments. Without this, a table of test
        // expectations — a row ending in `"ITEM_SINGLE"` above a row beginning
        // with `"name"` — was read as `ITEM_SINGLE.name`, and eleven such
        // phantoms reached the committed register before anyone looked
        // (`lib:A-31`).
        if pair[1].1.trim() != "," {
            continue;
        }
        if !class.is_empty()
            && class
                .chars()
                .all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit())
            && !invariant.is_empty()
            // Identifier-shaped only. A second argument that is a sentence is a
            // detail message, not a name.
            && invariant
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_')
            // A name, not another class: `("EHR", "CONTRIBUTION")` is a type
            // check's two arguments, not a citation.
            && invariant.chars().any(|c| c.is_ascii_lowercase())
        {
            out.push((class.to_owned(), invariant.to_owned()));
        }
    }
    out.sort();
    out.dedup();
    out
}

/// Reports which openEHR RM invariants the `openehr` crate **names**.
///
/// # What this measures, and what it does not
///
/// It greps the crate's source for each invariant's name. That is weak evidence
/// and is labelled as such: a name present means somebody wrote the rule down
/// next to code, not that the code enforces it, and a name absent means only
/// that this crude test did not find it.
///
/// It is still worth having. Before this existed, "which RM invariants does the
/// crate enforce?" had no answer at all, and the two that turned out to be
/// neither enforced nor declared (`lib:A-19`, `COMPOSITION.Territory_valid` and
/// `Language_valid`) were invisible. A weak measure that is honest about being
/// weak beats no measure, provided nobody promotes it to a conformance claim —
/// which `C0.20` forbids.
///
/// The invariants come from `assets/rm-1.1.0-invariants.json`, distilled from
/// the openEHR BMM. The BMM carries the **expressions**, not merely the names,
/// which is what made this checkable at all.
/// How an invariant the crate does not **name** is accounted for.
///
/// The coverage report used to end at "not named" and say that telling these
/// apart "needs a human". That sentence was true for as long as nobody did it,
/// and while it stood, a genuine gap was indistinguishable from a class this
/// crate deliberately does not model. Starting the work found `lib:A-23` within
/// the hour.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Disposition {
    /// The class is outside the crate's declared scope.
    Excluded,
    /// The invariant cannot fail in Rust: an empty `Vec` *is* openEHR's absent
    /// case, or the predicate is derived from the field it constrains.
    Vacuous,
    /// Enforced, under a name openEHR does not use. An `lib:L10.4` defect: the
    /// rule holds and a reader cannot find it from the class definition.
    Renamed,
    /// Genuinely not enforced.
    Unenforced,
}

impl Disposition {
    const fn heading(self) -> &'static str {
        match self {
            Self::Excluded => "Out of scope",
            Self::Vacuous => "Cannot fail in Rust",
            Self::Renamed => "Enforced under another name (`lib:L10.4`)",
            Self::Unenforced => "**Not enforced**",
        }
    }
}

/// Why each unnamed invariant is not named.
///
/// Every invariant the grep does not find MUST appear here, or the build fails.
/// That is the point: a new RM release, or a rename, cannot quietly add an
/// unexamined rule to a list nobody reads to the bottom of.
const DISPOSITIONS: &[(&str, &str, Disposition, &str)] = &[
    // --- out of scope: the Archetype Model and authored resources (lib:S1.4) --
    (
        "AUTHORED_RESOURCE",
        "Current_revision_valid",
        Disposition::Excluded,
        "no archetype or template is modelled",
    ),
    (
        "AUTHORED_RESOURCE",
        "Description_valid",
        Disposition::Excluded,
        "no archetype or template is modelled",
    ),
    (
        "AUTHORED_RESOURCE",
        "Languages_available_valid",
        Disposition::Excluded,
        "no archetype or template is modelled",
    ),
    (
        "AUTHORED_RESOURCE",
        "Original_language_valid",
        Disposition::Excluded,
        "no archetype or template is modelled",
    ),
    (
        "AUTHORED_RESOURCE",
        "Revision_history_valid",
        Disposition::Excluded,
        "no archetype or template is modelled",
    ),
    (
        "AUTHORED_RESOURCE",
        "Translations_valid",
        Disposition::Excluded,
        "no archetype or template is modelled",
    ),
    (
        "RESOURCE_DESCRIPTION",
        "Details_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION",
        "Language_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION",
        "Original_author_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION",
        "Parent_resource_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION_ITEM",
        "Language_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION_ITEM",
        "Purpose_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION_ITEM",
        "Use_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION_ITEM",
        "copyright_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "RESOURCE_DESCRIPTION_ITEM",
        "misuse_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "TRANSLATION_DETAILS",
        "Language_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    // --- out of scope: EHR Extract (lib:S1.6) -------------------------------
    (
        "EXTRACT",
        "Sequence_nr_valid",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "EXTRACT_CONTENT_ITEM",
        "Item_validity",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "EXTRACT_UPDATE_SPEC",
        "Overall_validity",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "EXTRACT_UPDATE_SPEC",
        "Send_changes_only_validity",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "EXTRACT_UPDATE_SPEC",
        "Trigger_events_validity",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "EXTRACT_VERSION_SPEC",
        "Includes_revision_history_valid",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    // --- out of scope: classes this crate does not carry ---------------------
    (
        "ITEM_TAG",
        "Inv_key_valid",
        Disposition::Excluded,
        "ITEM_TAG is an RM 1.1.0 addition this crate does not model",
    ),
    (
        "ITEM_TAG",
        "Inv_value_valid",
        Disposition::Excluded,
        "ITEM_TAG is an RM 1.1.0 addition this crate does not model",
    ),
    (
        "VERSIONED_COMPOSITION",
        "Persistent_validity",
        Disposition::Excluded,
        "VERSIONED_OBJECT is generic here; no COMPOSITION-specific subtype exists",
    ),
    // --- out of scope: demographics are values, not a navigable repository ---
    //
    // These four constrain a *graph*: that a relationship's source is the party
    // holding it, and that the demographic repository can be asked for the
    // reverse. The crate models demographics as values with no back-references
    // and no repository to consult, so there is nothing to check against.
    // Recorded as an exclusion that is **not yet declared** in the library
    // specification — see `lib:A-24`.
    (
        "PARTY",
        "Relationships_validity",
        Disposition::Excluded,
        "no demographic repository is modelled (undeclared: lib:A-24)",
    ),
    (
        "PARTY",
        "Reverse_relationships_validity",
        Disposition::Excluded,
        "no demographic repository is modelled (undeclared: lib:A-24)",
    ),
    (
        "PARTY_RELATIONSHIP",
        "Source_valid",
        Disposition::Excluded,
        "no demographic repository is modelled (undeclared: lib:A-24)",
    ),
    (
        "PARTY_RELATIONSHIP",
        "Target_valid",
        Disposition::Excluded,
        "no demographic repository is modelled (undeclared: lib:A-24)",
    ),
    // --- cannot fail: an empty Vec is openEHR's absent case ------------------
    (
        "ACTOR",
        "Roles_valid",
        Disposition::Vacuous,
        "roles is a Vec",
    ),
    (
        "COMPOSITION",
        "Content_valid",
        Disposition::Vacuous,
        "content is a Vec",
    ),
    (
        "DV_ORDERED",
        "Other_reference_ranges_validity",
        Disposition::Vacuous,
        "other_reference_ranges is a Vec",
    ),
    (
        "DV_TEXT",
        "Mappings_valid",
        Disposition::Vacuous,
        "mappings is a Vec",
    ),
    (
        "ENTRY",
        "Other_participations_valid",
        Disposition::Vacuous,
        "other_participations is a Vec",
    ),
    (
        "EVENT_CONTEXT",
        "Participations_validity",
        Disposition::Vacuous,
        "participations is a Vec",
    ),
    (
        "LOCATABLE",
        "Links_valid",
        Disposition::Vacuous,
        "links is a Vec",
    ),
    (
        "PARTY",
        "Contacts_valid",
        Disposition::Vacuous,
        "contacts is a Vec",
    ),
    (
        "PARTY_IDENTIFIED",
        "Identifiers_valid",
        Disposition::Vacuous,
        "identifiers is a Vec",
    ),
    (
        "ROLE",
        "Capabilities_valid",
        Disposition::Vacuous,
        "capabilities is a Vec",
    ),
    // --- cannot fail: the predicate is derived from what it constrains -------
    (
        "ELEMENT",
        "Inv_is_null_valid",
        Disposition::Vacuous,
        "is_null() returns value.is_none()",
    ),
    (
        "LOCATABLE",
        "Archetyped_valid",
        Disposition::Vacuous,
        "is_archetype_root() returns archetype_details.is_some()",
    ),
    (
        "ORIGINAL_VERSION",
        "Is_merged_validity",
        Disposition::Vacuous,
        "is_merged() returns !other_input_version_uids.is_empty()",
    ),
    (
        "VERSIONED_OBJECT",
        "All_version_ids_valid",
        Disposition::Vacuous,
        "the count is the Vec's length",
    ),
    (
        "VERSIONED_OBJECT",
        "All_versions_valid",
        Disposition::Vacuous,
        "the count is the Vec's length",
    ),
    (
        "VERSIONED_OBJECT",
        "Version_count_valid",
        Disposition::Vacuous,
        "the count is a usize",
    ),
    (
        "ITEM_LIST",
        "Valid_structure",
        Disposition::Vacuous,
        "items is a Vec<Element>, so the element type is the constraint",
    ),
    // --- not enforced: needs a code set the crate does not carry (lib:S1.18) -
    (
        "COMPOSITION",
        "Language_valid",
        Disposition::Unenforced,
        "ISO 639 is not carried (lib:A-19)",
    ),
    (
        "COMPOSITION",
        "Territory_valid",
        Disposition::Unenforced,
        "ISO 3166 is not carried (lib:A-19)",
    ),
    (
        "DV_ENCAPSULATED",
        "Charset_valid",
        Disposition::Unenforced,
        "IANA character sets are not carried",
    ),
    (
        "DV_ENCAPSULATED",
        "Language_valid",
        Disposition::Unenforced,
        "ISO 639 is not carried",
    ),
    (
        "DV_TEXT",
        "Encoding_valid",
        Disposition::Unenforced,
        "IANA character sets are not carried",
    ),
    (
        "DV_TEXT",
        "Language_valid",
        Disposition::Unenforced,
        "ISO 639 is not carried",
    ),
    (
        "ENTRY",
        "Encoding_valid",
        Disposition::Unenforced,
        "IANA character sets are not carried",
    ),
    (
        "ENTRY",
        "Language_valid",
        Disposition::Unenforced,
        "ISO 639 is not carried",
    ),
    (
        "DV_MULTIMEDIA",
        "Media_type_valid",
        Disposition::Unenforced,
        "IANA media types are not carried",
    ),
    // --- not enforced, and the crate has what it would need ------------------
    (
        "VERSION",
        "Owner_id_valid",
        Disposition::Vacuous,
        "owner_id is a derived function, extracted from uid.object_id (BMM)",
    ),
    (
        "VERSIONED_OBJECT",
        "Latest_version_valid",
        Disposition::Vacuous,
        "latest_version() returns versions.last(); a derived function (BMM)",
    ),
    (
        "DV_ORDERED",
        "Is_simple_validity",
        Disposition::Vacuous,
        "is_simple is derived as `no reference ranges`; the rule restates it (BMM)",
    ),
    (
        "EVENT",
        "Offset_validity1",
        Disposition::Vacuous,
        "offset is a derived function, computed as time.diff(parent.origin) (BMM); the crate stores none",
    ),
    (
        "INTERVAL_EVENT",
        "Interval_start_time_valid",
        Disposition::Vacuous,
        "interval_start_time is derived; the crate computes it from time - width (BMM)",
    ),
    (
        "CONTACT",
        "Purpose_valid",
        Disposition::Vacuous,
        "purpose is derived from the inherited name (BMM)",
    ),
    (
        "PARTY_IDENTITY",
        "Purpose_valid",
        Disposition::Vacuous,
        "purpose is derived from the inherited name (BMM)",
    ),
    // --- revealed once the count became class-aware (lib:A-25) ---------------
    //
    // Every one of these was counted as *named* because some other class's rule
    // shares the name, or because a comment mentioned it. `Language_valid`
    // belongs to seven classes and `Value_valid` to six.

    // Enforced, reported under a name openEHR does not use.
    (
        "DV_DATE",
        "Value_valid",
        Disposition::Renamed,
        "the ISO 8601 parser refuses invalid text and reports itself, not DV_DATE",
    ),
    (
        "DV_DATE_TIME",
        "Value_valid",
        Disposition::Renamed,
        "as DV_DATE",
    ),
    ("DV_TIME", "Value_valid", Disposition::Renamed, "as DV_DATE"),
    (
        "DV_DURATION",
        "Value_valid",
        Disposition::Renamed,
        "as DV_DATE",
    ),
    (
        "DV_URI",
        "Value_valid",
        Disposition::Renamed,
        "the URI parser refuses invalid text and reports itself",
    ),
    (
        "VERSION",
        "Lifecycle_state_ valid",
        Disposition::Renamed,
        "checked and cited as ORIGINAL_VERSION; openEHR declares it on VERSION",
    ),
    // Cannot fail.
    (
        "ATTESTATION",
        "Items_valid",
        Disposition::Vacuous,
        "items is a Vec",
    ),
    (
        "ORIGINAL_VERSION",
        "Attestations_valid",
        Disposition::Vacuous,
        "attestations is a Vec",
    ),
    (
        "ORIGINAL_VERSION",
        "Other_input_version_uids_valid",
        Disposition::Vacuous,
        "other_input_version_uids is a Vec",
    ),
    (
        "SECTION",
        "Items_valid",
        Disposition::Vacuous,
        "items is a Vec",
    ),
    (
        "DV_PARSABLE",
        "Size_valid",
        Disposition::Vacuous,
        "size is not stored, so it cannot disagree with the value's length",
    ),
    // Out of scope.
    (
        "EXTRACT_PARTICIPATION",
        "Function_valid",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "EXTRACT_PARTICIPATION",
        "Mode_valid",
        Disposition::Excluded,
        "EHR Extract is not modelled",
    ),
    (
        "RESOURCE_DESCRIPTION",
        "Lifecycle_state_valid",
        Disposition::Excluded,
        "describes an authored resource",
    ),
    (
        "VERSIONED_COMPOSITION",
        "Archetype_node_id_valid",
        Disposition::Excluded,
        "VERSIONED_COMPOSITION is not modelled",
    ),
    // Not enforced.
    (
        "ADDRESS",
        "Type_valid",
        Disposition::Vacuous,
        "type is derived from the inherited name (BMM)",
    ),
    (
        "EHR_ACCESS",
        "Scheme_valid",
        Disposition::Unenforced,
        "a declared departure: EhrAccess::new records no policy, and `no policy set` is not `deny all`",
    ),
    (
        "PARTY",
        "Type_valid",
        Disposition::Vacuous,
        "type is a derived function (BMM)",
    ),
    (
        "PARTY_RELATIONSHIP",
        "Type_validity",
        Disposition::Vacuous,
        "type is a derived function (BMM)",
    ),
];

// One narrative: read the source, decide what is named, account for what is
// not, then write it out. Splitting it would put the accounting in one place and
// the report of the accounting in another, and the report is the only reason the
// accounting exists.
#[allow(clippy::too_many_lines)]
fn invariant_coverage(root: &Path) -> Asset {
    let raw = std::fs::read_to_string(root.join("assets/rm-1.1.0-invariants.json"))
        .expect("assets/rm-1.1.0-invariants.json is committed");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("invariants parse");
    let classes: BTreeMap<String, BTreeMap<String, String>> =
        serde_json::from_value(doc["classes"].clone()).expect("classes parse");

    // Read every Rust source file in the library.
    let mut source = String::new();
    let mut stack = vec![root.join("openehr/src")];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("read openehr/src").flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "rs") {
                source.push_str(&std::fs::read_to_string(&path).expect("read source"));
                source.push('\n');
            }
        }
    }

    // `lib:L10.4` requires the crate to report openEHR's *own* invariant names,
    // so a reader can find the rule in the class definition. A prior audit
    // found five violations by hand and said "and three more" without naming
    // them. This finds them all, every time it runs.
    let cited = regex_citations(&source);
    let mut divergent: Vec<(String, String, Vec<String>)> = Vec::new();
    for (class, ours) in &cited {
        if let Some(theirs) = classes.get(class)
            && !theirs.contains_key(ours)
        {
            divergent.push((
                class.clone(),
                ours.clone(),
                theirs.keys().cloned().collect(),
            ));
        }
    }
    divergent.sort();

    let mut named = 0usize;
    let mut unnamed: Vec<(String, String)> = Vec::new();
    for (class, invariants) in &classes {
        for name in invariants.keys() {
            // The **pair**, not the name. A bare substring search counts an
            // invariant as named when some *other* class's rule happens to
            // share its name — openEHR reuses 15 of them, `Language_valid`
            // across seven classes and `Value_valid` across six — and counts a
            // name written in a comment saying the rule is *not* checked. Both
            // are false passes, and this file exists to remove exactly that
            // kind of ambiguity (`lib:A-25`).
            //
            // `cited` comes from parsing the two call forms that report an
            // invariant, so a match means the crate can actually name this rule
            // when it fails.
            //
            // The BMM has stray spaces in a few names ("Lifecycle_state_ valid").
            let squashed = name.replace(' ', "");
            let underscored = name.replace(' ', "_");
            if cited
                .iter()
                .any(|(c, n)| c == class && (n == name || *n == squashed || *n == underscored))
            {
                named += 1;
            } else {
                unnamed.push((class.clone(), name.clone()));
            }
        }
    }
    let total = named + unnamed.len();

    // Every unnamed invariant must be accounted for, and every disposition must
    // still be needed. Both directions fail the build.
    //
    // The second direction matters as much as the first: a disposition left
    // behind after its invariant *is* named would keep asserting a reason that
    // no longer applies, which is how a register comes to describe a codebase
    // that has moved on (`db:C0.20`).
    let dispositioned: BTreeMap<(&str, &str), (Disposition, &str)> = DISPOSITIONS
        .iter()
        .map(|(class, name, kind, why)| ((*class, *name), (*kind, *why)))
        .collect();
    let missing: Vec<String> = unnamed
        .iter()
        .filter(|(c, n)| !dispositioned.contains_key(&(c.as_str(), n.as_str())))
        .map(|(c, n)| format!("{c}.{n}"))
        .collect();
    assert!(
        missing.is_empty(),
        "invariants named nowhere and dispositioned nowhere: {}\n\
         Add each to DISPOSITIONS in openehr-assets, with a reason. \
         An invariant nobody has looked at must not sit in a list that reads as \
         a pass (`W0.4`).",
        missing.join(", ")
    );
    let stale: Vec<String> = dispositioned
        .keys()
        .filter(|(c, n)| !unnamed.iter().any(|(uc, un)| uc == c && un == n))
        .map(|(c, n)| format!("{c}.{n}"))
        .collect();
    assert!(
        stale.is_empty(),
        "dispositions for invariants the crate now names: {}\n\
         Remove them: the reason recorded no longer applies.",
        stale.join(", ")
    );

    let mut body = String::new();
    body.push_str(
        "# RM invariant coverage\n\n\
         GENERATED by `openehr-assets`. Do not edit.\n\n\
         ## What this is\n\n\
         Every invariant openEHR RM 1.1.0 declares, against whether the `openehr`\n\
         crate's source **names** it.\n\n\
         **Naming is not enforcing.** This is a grep. A name present means the\n\
         rule was written down beside code; a name absent means only that this\n\
         crude test did not find it. It MUST NOT be promoted to a conformance\n\
         claim (`db:C0.20`) — the [conformance matrix](../spec/databases/conformance-matrix.md)\n\
         is where verified status lives.\n\n\
         It is still worth having: before it existed, the question had no answer,\n\
         and the two invariants that turned out to be neither enforced nor\n\
         declared were invisible (`lib:A-19`).\n\n\
         Source: the openEHR BMM, which carries invariant **expressions** and not\n\
         merely names — see `rm-1.1.0-invariants.json`.\n\n",
    );
    let _ = writeln!(body, "## Summary\n");
    let _ = writeln!(body, "| | Count |");
    let _ = writeln!(body, "| --- | --- |");
    let _ = writeln!(body, "| Invariants in RM 1.1.0 | {total} |");
    let _ = writeln!(body, "| Named in the crate's source | {named} |");
    let _ = writeln!(body, "| Not named | {} |", unnamed.len());
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for (class, name) in &unnamed {
        let (kind, _) = dispositioned[&(class.as_str(), name.as_str())];
        *counts.entry(kind.heading()).or_default() += 1;
    }
    let _ = writeln!(
        body,
        "\nEvery not-named invariant is accounted for below, and the build fails \
         if one is not (`W0.4`). This file used to say that telling them apart \
         \"needs a human\" — which was true only for as long as nobody did it, \
         and while it stood a genuine gap was indistinguishable from a class \
         this crate deliberately does not model.\n"
    );
    for (heading, count) in &counts {
        let _ = writeln!(body, "- {heading}: **{count}**");
    }
    let _ = writeln!(body);
    // An addition is only legitimate once declared (`lib:L10.9`). Reading the
    // register out of the spec means the report cannot drift from it.
    let declared =
        std::fs::read_to_string(root.join("openehr/spec/10-validation.md")).unwrap_or_default();

    // `lib:L10.11`: the same for the other direction. An openEHR invariant the
    // crate does not enforce must be declared, and the declaration must match
    // what this report found.
    //
    // Both directions fail the build. A rule quietly abandoned appears here and
    // not in the register; a rule quietly enforced appears in the register and
    // not here. Either way the two documents disagree, and the one a reader
    // trusts is whichever they opened.
    let registered: BTreeSet<(String, String)> = declared
        .lines()
        .skip_while(|line| !line.starts_with("### Unenforced openEHR checks"))
        .take_while(|line| !line.starts_with("### Crate-added checks"))
        .filter_map(|line| {
            let mut cells = line.split('|').map(str::trim);
            let (class, invariant) = (cells.nth(1)?, cells.next()?);
            let unquote = |c: &str| c.trim_matches('`').to_owned();
            (class.starts_with('`') && invariant.starts_with('`'))
                .then(|| (unquote(class), unquote(invariant)))
        })
        .collect();
    let found: BTreeSet<(String, String)> = unnamed
        .iter()
        .filter(|(c, n)| dispositioned[&(c.as_str(), n.as_str())].0 == Disposition::Unenforced)
        .cloned()
        .collect();
    assert_eq!(
        found,
        registered,
        "\nthe unenforced invariants and `lib:L10.11`'s register disagree.\n\
         In the report and not the register: {:?}\n\
         In the register and not the report: {:?}\n\
         Declare an abandoned rule, or delete a declaration for one now enforced.",
        found.difference(&registered).collect::<Vec<_>>(),
        registered.difference(&found).collect::<Vec<_>>()
    );
    write_divergences(&mut body, &divergent, &declared);
    let _ = writeln!(body, "## Not named in the crate's source\n");
    let _ = writeln!(
        body,
        "Grouped by why. **Not enforced** is the only group that is a gap; the \
         others are answers.\n"
    );
    for kind in [
        Disposition::Unenforced,
        Disposition::Renamed,
        Disposition::Vacuous,
        Disposition::Excluded,
    ] {
        let rows: Vec<_> = unnamed
            .iter()
            .filter(|(c, n)| dispositioned[&(c.as_str(), n.as_str())].0 == kind)
            .collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(body, "### {} — {}\n", kind.heading(), rows.len());
        let _ = writeln!(body, "| Class | Invariant | Why |");
        let _ = writeln!(body, "| --- | --- | --- |");
        for (class, name) in rows {
            let why = dispositioned[&(class.as_str(), name.as_str())].1;
            let _ = writeln!(body, "| `{class}` | `{name}` | {why} |");
        }
        let _ = writeln!(body);
    }
    Asset {
        path: root.join("assets/invariant-coverage.md"),
        body,
    }
}

/// The `L10.4` section of the coverage report.
fn write_divergences(
    body: &mut String,
    divergent: &[(String, String, Vec<String>)],
    declared: &str,
) {
    let _ = writeln!(
        body,
        "## Invariant names that diverge from openEHR (`lib:L10.4`)\n"
    );
    let _ = writeln!(
        body,
        "`L10.4` requires the crate to report openEHR's own invariant names, so a reader can find the rule in the class definition. A name the specification does not contain fails that.\n\nOnly classes openEHR gives invariants to are listed; where openEHR states none, a crate rule is an addition rather than a rename.\n"
    );
    if divergent.is_empty() {
        let _ = writeln!(body, "None.\n");
    } else {
        let _ = writeln!(
            body,
            "| Class | Crate reports | Declared (`lib:L10.9`) | openEHR declares |"
        );
        let _ = writeln!(body, "| --- | --- | --- | --- |");
        for (class, ours, theirs) in divergent {
            let mark = if declared.contains(&format!("| `{ours}` |")) {
                "yes"
            } else {
                "**NO**"
            };
            let _ = writeln!(
                body,
                "| `{class}` | `{ours}` | {mark} | {} |",
                theirs
                    .iter()
                    .map(|t| format!("`{t}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let _ = writeln!(body);
    }
}

fn main() -> std::process::ExitCode {
    let mode = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "write".to_owned());
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repository root")
        .to_path_buf();
    let assets = build(&root);

    match mode.as_str() {
        "write" => {
            for asset in &assets {
                if let Some(parent) = asset.path.parent() {
                    std::fs::create_dir_all(parent).expect("create assets directory");
                }
                std::fs::write(&asset.path, &asset.body).expect("write asset");
                println!("wrote {}", asset.path.display());
            }
            std::process::ExitCode::SUCCESS
        }
        "check" => {
            let mut stale = Vec::new();
            for asset in &assets {
                let current = std::fs::read_to_string(&asset.path).unwrap_or_default();
                if current != asset.body {
                    stale.push(asset.path.display().to_string());
                }
            }
            if stale.is_empty() {
                println!("assets are current ({} files)", assets.len());
                std::process::ExitCode::SUCCESS
            } else {
                eprintln!("stale assets — run `cargo run -- write` in openehr-assets/:");
                for path in &stale {
                    eprintln!("  {path}");
                }
                std::process::ExitCode::FAILURE
            }
        }
        other => {
            eprintln!("usage: openehr-assets [write|check]  (got {other:?})");
            std::process::ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{DISPOSITIONS, regex_citations};

    /// Every failure mode this function has actually had.
    ///
    /// It had none of these tests while three findings in a row — `lib:A-24`,
    /// `lib:A-25`, and `A-25`'s own correction — were about it being wrong.
    /// A measuring instrument with no tests measures whatever it happens to do.
    #[test]
    fn a_citation_is_recognised_in_every_form_that_reports_one() {
        let source = r#"
            ctx.violation("EHR", "Ehr_status_valid", "detail");
            return Err(ParseError::invariant("VERSION", "Owner_id_valid"));
            check_optional_group(x, GROUP, "PARTICIPATION", "Function_valid", ctx);
            check_party(p, "AUDIT_DETAILS", "Committer_valid", ctx);
        "#;
        let cited = regex_citations(source);
        for expected in [
            ("EHR", "Ehr_status_valid"),
            ("VERSION", "Owner_id_valid"),
            // The helper forms. Enumerating call sites is what made
            // `ATTESTATION.Reason_valid` look unenforced when it was not.
            ("PARTICIPATION", "Function_valid"),
            ("AUDIT_DETAILS", "Committer_valid"),
        ] {
            assert!(
                cited.contains(&(expected.0.to_owned(), expected.1.to_owned())),
                "{expected:?} not cited in {cited:?}"
            );
        }
    }

    #[test]
    fn a_comment_never_counts_as_a_citation() {
        // A note explaining that a rule is *deliberately* not checked is the
        // most likely thing to be written next to one, and counting it makes
        // the report say the opposite of what the comment says.
        let source = r#"
            // "ATTESTATION", "Items_valid" cannot fail: items is a Vec.
            /// `DV_TEXT`, "Mappings_valid" is vacuous here.
            /* "SECTION", "Items_valid" likewise. */
            let x = 1;
        "#;
        assert!(
            regex_citations(source).is_empty(),
            "{:?}",
            regex_citations(source)
        );
    }

    #[test]
    fn a_double_slash_inside_a_string_does_not_desynchronise_the_scan() {
        // The regression that matters most. Skipping comments by searching for
        // `//` truncated `"https://…"` mid-literal and put every quote after it
        // out of phase, silently un-naming forty rules that were fine. The
        // citation below sits *after* the URL, and is the whole point.
        let source = r#"
            let url = "https://example.invalid/spec#anchor";
            ctx.violation("EHR", "Ehr_access_valid", "detail");
        "#;
        assert_eq!(
            regex_citations(source),
            vec![("EHR".to_owned(), "Ehr_access_valid".to_owned())]
        );
    }

    #[test]
    fn an_escaped_quote_does_not_end_a_literal() {
        let source = r#"
            let s = "a \" b";
            ctx.violation("EHR", "Ehr_status_valid", "detail");
        "#;
        assert_eq!(
            regex_citations(source),
            vec![("EHR".to_owned(), "Ehr_status_valid".to_owned())]
        );
    }

    #[test]
    fn two_class_names_are_not_a_citation() {
        // `ObjectRef::new("local", "EHR", …)` and type comparisons put two
        // SCREAMING literals side by side. An invariant name has a lower-case
        // letter; a class name does not.
        let source = r#"
            let r = ObjectRef::new("LOCAL", "VERSIONED_COMPOSITION", id);
        "#;
        assert!(
            regex_citations(source).is_empty(),
            "{:?}",
            regex_citations(source)
        );
    }

    #[test]
    fn a_raw_string_is_skipped_whole() {
        // A JSON fixture must not manufacture a citation from its own inner
        // quotes.
        let json = "let j = r#\"{\"EHR\": {\"Ehr_status_valid\": 1}}\"#;";
        assert!(
            regex_citations(json).is_empty(),
            "a JSON fixture produced {:?}",
            regex_citations(json)
        );

        // The case that separates handling raw strings from being lucky: an
        // **odd** number of quotes inside one. Reading it as an ordinary
        // literal leaves every quote after it out of phase, so the real
        // citation below is missed — which is exactly how forty rules were
        // silently un-named once already.
        let odd =
            "let q = r#\"he said \"hi\"#;\nctx.violation(\"EHR\", \"Ehr_status_valid\", \"d\");";
        assert_eq!(
            regex_citations(odd),
            vec![("EHR".to_owned(), "Ehr_status_valid".to_owned())],
            "a raw string put the scan out of phase"
        );
    }

    #[test]
    fn an_r_that_merely_ends_an_identifier_is_not_a_raw_string() {
        // `char`, `for`, `our` — any identifier ending in `r` sits next to
        // whatever follows it, and treating that `r` as a raw-string opener
        // would swallow the rest of the file.
        let source = r#"
            let c: char = 'x';
            for _ in 0..1 {}
            ctx.violation("EHR", "Ehr_status_valid", "detail");
        "#;
        assert_eq!(
            regex_citations(source),
            vec![("EHR".to_owned(), "Ehr_status_valid".to_owned())]
        );
    }

    #[test]
    fn no_disposition_is_listed_twice() {
        let mut seen = std::collections::BTreeSet::new();
        for (class, name, _, _) in DISPOSITIONS {
            assert!(
                seen.insert((*class, *name)),
                "{class}.{name} is dispositioned twice"
            );
        }
    }

    /// Two literals that are not one call's arguments are not a citation.
    ///
    /// The scanner matched **any** uppercase literal followed by an
    /// identifier-shaped one, which is what let it read a helper's arguments
    /// without an enumerated list of call forms (`lib:A-25`). The cost of that
    /// generality was measured when a table of test expectations landed in
    /// `path.rs`: a row ending `"ITEM_SINGLE"` above a row beginning `"name"`
    /// became `ITEM_SINGLE.name`, and eleven such phantoms — `ROLE._type`,
    /// `EHR_STATUS._type`, `ELEMENT.archetype_node_id` among them — were in
    /// the committed register (`lib:A-31`).
    ///
    /// The fix keeps the generality and adds the one thing a citation always
    /// has: the two literals are separated by a comma and nothing else.
    #[test]
    fn only_two_literals_in_one_argument_list_are_a_citation() {
        // The real forms, including one split across lines.
        assert_eq!(
            regex_citations(r#"ParseError::invariant("ELEMENT", "Inv_null_valid")"#),
            vec![("ELEMENT".to_owned(), "Inv_null_valid".to_owned())]
        );
        assert_eq!(
            regex_citations("check_party(\n    p,\n    \"PARTY\",\n    \"Name_valid\",\n)"),
            vec![("PARTY".to_owned(), "Name_valid".to_owned())]
        );

        // A table of expectations. Adjacent, but in different rows.
        let table = r#"
            let cases = &[
                (Node::Entry(&instruction), "activities", "ITEM_SINGLE"),
                (Node::Entry(&instruction), "name", "DV_TEXT"),
            ];
        "#;
        assert!(
            regex_citations(table).is_empty(),
            "a test table was read as citations: {:?}",
            regex_citations(table)
        );

        // A macro invocation followed later by an unrelated literal.
        let macros = "impl_locatable!(Element, \"ELEMENT\");\nlet x = \"archetype_node_id\";";
        assert!(
            regex_citations(macros).is_empty(),
            "{:?}",
            regex_citations(macros)
        );
    }
}
