-- openEHR schema for MariaDB
--
-- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`
-- in openehr-assets/ and commit the diff.
--
-- Committed so that a change to the schema or to a dialect is visible
-- as a diff at review time, and so that two dialects becoming the same
-- thing shows up as two identical files (spec/audit.md W-01).

CREATE TABLE IF NOT EXISTS `openehr_schema_version` (
  `version` BIGINT NOT NULL,
  `applied_text` VARCHAR(64) NOT NULL,
  `applied_utc` DATETIME(6),
  PRIMARY KEY (`version`)
);

CREATE TABLE IF NOT EXISTS `openehr_ehr` (
  `ehr_id` VARCHAR(255) NOT NULL,
  `system_id` VARCHAR(255) NOT NULL,
  `time_created_text` VARCHAR(64) NOT NULL,
  `time_created_utc` DATETIME(6),
  `ehr_status_uid` VARCHAR(255) NOT NULL,
  `ehr_access_uid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ehr_id`)
);

CREATE TABLE IF NOT EXISTS `openehr_versioned_object` (
  `uid` VARCHAR(255) NOT NULL,
  `ehr_id` VARCHAR(255) NOT NULL,
  `rm_type` VARCHAR(64) NOT NULL,
  `time_created_text` VARCHAR(64) NOT NULL,
  `time_created_utc` DATETIME(6),
  PRIMARY KEY (`uid`),
  FOREIGN KEY (`ehr_id`) REFERENCES `openehr_ehr` (`ehr_id`)
);

CREATE TABLE IF NOT EXISTS `openehr_version` (
  `uid` VARCHAR(255) NOT NULL,
  `versioned_object_uid` VARCHAR(255) NOT NULL,
  `creating_system_id` VARCHAR(255) NOT NULL,
  `trunk_version` BIGINT NOT NULL,
  `branch_number` BIGINT,
  `branch_version` BIGINT,
  `preceding_version_uid` VARCHAR(255),
  `lifecycle_state_code` VARCHAR(16) NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL,
  `contribution_uid` VARCHAR(255) NOT NULL,
  `audit_system_id` VARCHAR(255) NOT NULL,
  `audit_change_type_code` VARCHAR(16) NOT NULL,
  `audit_committer_name` VARCHAR(255),
  `audit_time_committed_text` VARCHAR(64) NOT NULL,
  `audit_time_committed_utc` DATETIME(6),
  `data_json` JSON,
  `audit_description` LONGTEXT,
  `signature` LONGTEXT,
  `attestations_json` JSON,
  `other_input_version_uids_json` JSON,
  `chain_previous` BINARY(32) NOT NULL,
  `chain_content` BINARY(32) NOT NULL,
  `chain_digest` BINARY(32) NOT NULL,
  `chain_tag_key_id` VARCHAR(255),
  `chain_tag_mac` BINARY(32),
  PRIMARY KEY (`uid`),
  FOREIGN KEY (`versioned_object_uid`) REFERENCES `openehr_versioned_object` (`uid`)
);

CREATE TABLE IF NOT EXISTS `openehr_contribution` (
  `uid` VARCHAR(255) NOT NULL,
  `ehr_id` VARCHAR(255) NOT NULL,
  `audit_change_type_code` VARCHAR(16) NOT NULL,
  `audit_system_id` VARCHAR(255) NOT NULL,
  `audit_committer_name` VARCHAR(255),
  `audit_time_committed_text` VARCHAR(64) NOT NULL,
  `audit_time_committed_utc` DATETIME(6),
  PRIMARY KEY (`uid`),
  FOREIGN KEY (`ehr_id`) REFERENCES `openehr_ehr` (`ehr_id`)
);

CREATE TABLE IF NOT EXISTS `openehr_composition_index` (
  `version_uid` VARCHAR(255) NOT NULL,
  `ehr_id` VARCHAR(255) NOT NULL,
  `archetype_id` VARCHAR(255) NOT NULL,
  `template_id` VARCHAR(255),
  `category_code` VARCHAR(16) NOT NULL,
  `composer_name` VARCHAR(255),
  `language_code` VARCHAR(32) NOT NULL,
  `territory_code` VARCHAR(32) NOT NULL,
  `setting_code` VARCHAR(16),
  `context_start_text` VARCHAR(64),
  `context_start_utc` DATETIME(6),
  `context_end_text` VARCHAR(64),
  `context_end_utc` DATETIME(6),
  PRIMARY KEY (`version_uid`),
  FOREIGN KEY (`version_uid`) REFERENCES `openehr_version` (`uid`)
);

CREATE INDEX IF NOT EXISTS `ix_versioned_object_ehr` ON `openehr_versioned_object` (`ehr_id`, `rm_type`);

CREATE UNIQUE INDEX IF NOT EXISTS `ix_version_container_trunk` ON `openehr_version` (`versioned_object_uid`, `trunk_version`, `branch_number`, `branch_version`);

CREATE INDEX IF NOT EXISTS `ix_version_time` ON `openehr_version` (`versioned_object_uid`, `audit_time_committed_utc`);

CREATE INDEX IF NOT EXISTS `ix_version_preceding` ON `openehr_version` (`preceding_version_uid`);

CREATE INDEX IF NOT EXISTS `ix_contribution_ehr_time` ON `openehr_contribution` (`ehr_id`, `audit_time_committed_utc`);

CREATE INDEX IF NOT EXISTS `ix_composition_archetype` ON `openehr_composition_index` (`ehr_id`, `archetype_id`);

CREATE INDEX IF NOT EXISTS `ix_composition_context_start` ON `openehr_composition_index` (`ehr_id`, `context_start_utc`);

CREATE OR REPLACE TRIGGER `trg_openehr_version_no_update` BEFORE UPDATE ON `openehr_version` FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'openehr_version is append-only (openEHR V8.10)';

CREATE OR REPLACE TRIGGER `trg_openehr_version_no_delete` BEFORE DELETE ON `openehr_version` FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'openehr_version is append-only (openEHR V8.10)';

CREATE OR REPLACE TRIGGER `trg_openehr_contribution_no_update` BEFORE UPDATE ON `openehr_contribution` FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'openehr_contribution is append-only (openEHR V8.10)';

CREATE OR REPLACE TRIGGER `trg_openehr_contribution_no_delete` BEFORE DELETE ON `openehr_contribution` FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'openehr_contribution is append-only (openEHR V8.10)';
