-- openEHR schema for SQL Server
--
-- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`
-- in openehr-assets/ and commit the diff.
--
-- Committed so that a change to the schema or to a dialect is visible
-- as a diff at review time, and so that two dialects becoming the same
-- thing shows up as two identical files (spec/audit.md W-01).

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'openehr_schema_version' AND type = 'U')
  EXEC('CREATE TABLE [openehr_schema_version] (
  [version] bigint NOT NULL,
  [applied_text] nvarchar(64) NOT NULL,
  [applied_utc] datetimeoffset(7),
  PRIMARY KEY ([version])
)');

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'openehr_ehr' AND type = 'U')
  EXEC('CREATE TABLE [openehr_ehr] (
  [ehr_id] nvarchar(255) NOT NULL,
  [system_id] nvarchar(255) NOT NULL,
  [time_created_text] nvarchar(64) NOT NULL,
  [time_created_utc] datetimeoffset(7),
  [ehr_status_uid] nvarchar(255) NOT NULL,
  [ehr_access_uid] nvarchar(255) NOT NULL,
  PRIMARY KEY ([ehr_id])
)');

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'openehr_versioned_object' AND type = 'U')
  EXEC('CREATE TABLE [openehr_versioned_object] (
  [uid] nvarchar(255) NOT NULL,
  [ehr_id] nvarchar(255) NOT NULL,
  [rm_type] nvarchar(64) NOT NULL,
  [time_created_text] nvarchar(64) NOT NULL,
  [time_created_utc] datetimeoffset(7),
  PRIMARY KEY ([uid]),
  FOREIGN KEY ([ehr_id]) REFERENCES [openehr_ehr] ([ehr_id])
)');

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'openehr_version' AND type = 'U')
  EXEC('CREATE TABLE [openehr_version] (
  [uid] nvarchar(255) NOT NULL,
  [versioned_object_uid] nvarchar(255) NOT NULL,
  [creating_system_id] nvarchar(255) NOT NULL,
  [trunk_version] bigint NOT NULL,
  [branch_number] bigint,
  [branch_version] bigint,
  [preceding_version_uid] nvarchar(255),
  [lifecycle_state_code] nvarchar(16) NOT NULL,
  [is_deleted] bit NOT NULL,
  [contribution_uid] nvarchar(255) NOT NULL,
  [audit_system_id] nvarchar(255) NOT NULL,
  [audit_change_type_code] nvarchar(16) NOT NULL,
  [audit_committer_name] nvarchar(255),
  [audit_time_committed_text] nvarchar(64) NOT NULL,
  [audit_time_committed_utc] datetimeoffset(7),
  [data_json] nvarchar(max),
  [audit_description] nvarchar(max),
  [signature] nvarchar(max),
  [attestations_json] nvarchar(max),
  [other_input_version_uids_json] nvarchar(max),
  [chain_previous] binary(32) NOT NULL,
  [chain_content] binary(32) NOT NULL,
  [chain_digest] binary(32) NOT NULL,
  [chain_tag_key_id] nvarchar(255),
  [chain_tag_mac] binary(32),
  PRIMARY KEY ([uid]),
  FOREIGN KEY ([versioned_object_uid]) REFERENCES [openehr_versioned_object] ([uid])
)');

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'openehr_contribution' AND type = 'U')
  EXEC('CREATE TABLE [openehr_contribution] (
  [uid] nvarchar(255) NOT NULL,
  [ehr_id] nvarchar(255) NOT NULL,
  [audit_change_type_code] nvarchar(16) NOT NULL,
  [audit_system_id] nvarchar(255) NOT NULL,
  [audit_committer_name] nvarchar(255),
  [audit_time_committed_text] nvarchar(64) NOT NULL,
  [audit_time_committed_utc] datetimeoffset(7),
  PRIMARY KEY ([uid]),
  FOREIGN KEY ([ehr_id]) REFERENCES [openehr_ehr] ([ehr_id])
)');

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'openehr_composition_index' AND type = 'U')
  EXEC('CREATE TABLE [openehr_composition_index] (
  [version_uid] nvarchar(255) NOT NULL,
  [ehr_id] nvarchar(255) NOT NULL,
  [archetype_id] nvarchar(255) NOT NULL,
  [template_id] nvarchar(255),
  [category_code] nvarchar(16) NOT NULL,
  [composer_name] nvarchar(255),
  [language_code] nvarchar(32) NOT NULL,
  [territory_code] nvarchar(32) NOT NULL,
  [setting_code] nvarchar(16),
  [context_start_text] nvarchar(64),
  [context_start_utc] datetimeoffset(7),
  [context_end_text] nvarchar(64),
  [context_end_utc] datetimeoffset(7),
  PRIMARY KEY ([version_uid]),
  FOREIGN KEY ([version_uid]) REFERENCES [openehr_version] ([uid])
)');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_versioned_object_ehr')
  EXEC('CREATE INDEX [ix_versioned_object_ehr] ON [openehr_versioned_object] ([ehr_id], [rm_type])');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_version_container_trunk')
  EXEC('CREATE UNIQUE INDEX [ix_version_container_trunk] ON [openehr_version] ([versioned_object_uid], [trunk_version], [branch_number], [branch_version])');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_version_time')
  EXEC('CREATE INDEX [ix_version_time] ON [openehr_version] ([versioned_object_uid], [audit_time_committed_utc])');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_version_preceding')
  EXEC('CREATE INDEX [ix_version_preceding] ON [openehr_version] ([preceding_version_uid])');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_contribution_ehr_time')
  EXEC('CREATE INDEX [ix_contribution_ehr_time] ON [openehr_contribution] ([ehr_id], [audit_time_committed_utc])');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_composition_archetype')
  EXEC('CREATE INDEX [ix_composition_archetype] ON [openehr_composition_index] ([ehr_id], [archetype_id])');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_composition_context_start')
  EXEC('CREATE INDEX [ix_composition_context_start] ON [openehr_composition_index] ([ehr_id], [context_start_utc])');

CREATE OR ALTER TRIGGER [trg_openehr_version_append_only] ON [openehr_version] INSTEAD OF UPDATE, DELETE AS BEGIN THROW 50000, 'openehr_version is append-only (openEHR V8.10)', 1; END;

CREATE OR ALTER TRIGGER [trg_openehr_contribution_append_only] ON [openehr_contribution] INSTEAD OF UPDATE, DELETE AS BEGIN THROW 50000, 'openehr_contribution is append-only (openEHR V8.10)', 1; END;
