-- openEHR schema for Oracle
--
-- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`
-- in openehr-assets/ and commit the diff.
--
-- Committed so that a change to the schema or to a dialect is visible
-- as a diff at review time, and so that two dialects becoming the same
-- thing shows up as two identical files (spec/audit.md W-01).

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "openehr_ehr" (
  "ehr_id" VARCHAR2(255 CHAR) NOT NULL,
  "system_id" VARCHAR2(255 CHAR) NOT NULL,
  "time_created_text" VARCHAR2(64 CHAR) NOT NULL,
  "time_created_utc" TIMESTAMP WITH TIME ZONE,
  "ehr_status_uid" VARCHAR2(255 CHAR) NOT NULL,
  "ehr_access_uid" VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY ("ehr_id")
)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "openehr_versioned_object" (
  "uid" VARCHAR2(255 CHAR) NOT NULL,
  "ehr_id" VARCHAR2(255 CHAR) NOT NULL,
  "rm_type" VARCHAR2(64 CHAR) NOT NULL,
  "time_created_text" VARCHAR2(64 CHAR) NOT NULL,
  "time_created_utc" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("ehr_id") REFERENCES "openehr_ehr" ("ehr_id")
)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "openehr_version" (
  "uid" VARCHAR2(255 CHAR) NOT NULL,
  "versioned_object_uid" VARCHAR2(255 CHAR) NOT NULL,
  "creating_system_id" VARCHAR2(255 CHAR) NOT NULL,
  "trunk_version" NUMBER(19) NOT NULL,
  "branch_number" NUMBER(19),
  "branch_version" NUMBER(19),
  "preceding_version_uid" VARCHAR2(255 CHAR),
  "lifecycle_state_code" VARCHAR2(16 CHAR) NOT NULL,
  "is_deleted" NUMBER(1) NOT NULL,
  "contribution_uid" VARCHAR2(255 CHAR) NOT NULL,
  "audit_system_id" VARCHAR2(255 CHAR) NOT NULL,
  "audit_change_type_code" VARCHAR2(16 CHAR) NOT NULL,
  "audit_committer_name" VARCHAR2(255 CHAR),
  "audit_time_committed_text" VARCHAR2(64 CHAR) NOT NULL,
  "audit_time_committed_utc" TIMESTAMP WITH TIME ZONE,
  "data_json" CLOB,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("versioned_object_uid") REFERENCES "openehr_versioned_object" ("uid")
)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "openehr_contribution" (
  "uid" VARCHAR2(255 CHAR) NOT NULL,
  "ehr_id" VARCHAR2(255 CHAR) NOT NULL,
  "audit_change_type_code" VARCHAR2(16 CHAR) NOT NULL,
  "audit_system_id" VARCHAR2(255 CHAR) NOT NULL,
  "audit_committer_name" VARCHAR2(255 CHAR),
  "audit_time_committed_text" VARCHAR2(64 CHAR) NOT NULL,
  "audit_time_committed_utc" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("ehr_id") REFERENCES "openehr_ehr" ("ehr_id")
)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "openehr_composition_index" (
  "version_uid" VARCHAR2(255 CHAR) NOT NULL,
  "ehr_id" VARCHAR2(255 CHAR) NOT NULL,
  "archetype_id" VARCHAR2(255 CHAR) NOT NULL,
  "template_id" VARCHAR2(255 CHAR),
  "category_code" VARCHAR2(16 CHAR) NOT NULL,
  "composer_name" VARCHAR2(255 CHAR),
  "language_code" VARCHAR2(32 CHAR) NOT NULL,
  "territory_code" VARCHAR2(32 CHAR) NOT NULL,
  "setting_code" VARCHAR2(16 CHAR),
  "context_start_text" VARCHAR2(64 CHAR),
  "context_start_utc" TIMESTAMP WITH TIME ZONE,
  "context_end_text" VARCHAR2(64 CHAR),
  "context_end_utc" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("version_uid"),
  FOREIGN KEY ("version_uid") REFERENCES "openehr_version" ("uid")
)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX "ix_versioned_object_ehr" ON "openehr_versioned_object" ("ehr_id", "rm_type")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "ix_version_container_trunk" ON "openehr_version" ("versioned_object_uid", "trunk_version", "branch_number", "branch_version")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX "ix_version_time" ON "openehr_version" ("versioned_object_uid", "audit_time_committed_utc")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX "ix_version_preceding" ON "openehr_version" ("preceding_version_uid")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX "ix_contribution_ehr_time" ON "openehr_contribution" ("ehr_id", "audit_time_committed_utc")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX "ix_composition_archetype" ON "openehr_composition_index" ("ehr_id", "archetype_id")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX "ix_composition_context_start" ON "openehr_composition_index" ("ehr_id", "context_start_utc")';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER "trg_openehr_version_append_only" BEFORE UPDATE OR DELETE ON "openehr_version" FOR EACH ROW BEGIN raise_application_error(-20001, 'openehr_version is append-only (openEHR V8.10)'); END;
/

CREATE OR REPLACE TRIGGER "trg_openehr_contribution_append_only" BEFORE UPDATE OR DELETE ON "openehr_contribution" FOR EACH ROW BEGIN raise_application_error(-20001, 'openehr_contribution is append-only (openEHR V8.10)'); END;
/
