-- openEHR schema for PostgreSQL
--
-- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`
-- in openehr-assets/ and commit the diff.
--
-- Committed so that a change to the schema or to a dialect is visible
-- as a diff at review time, and so that two dialects becoming the same
-- thing shows up as two identical files (spec/audit.md W-01).

CREATE TABLE IF NOT EXISTS "openehr_ehr" (
  "ehr_id" text NOT NULL,
  "system_id" text NOT NULL,
  "time_created_text" text NOT NULL,
  "time_created_utc" timestamptz,
  "ehr_status_uid" text NOT NULL,
  "ehr_access_uid" text NOT NULL,
  PRIMARY KEY ("ehr_id")
);

CREATE TABLE IF NOT EXISTS "openehr_versioned_object" (
  "uid" text NOT NULL,
  "ehr_id" text NOT NULL,
  "rm_type" text NOT NULL,
  "time_created_text" text NOT NULL,
  "time_created_utc" timestamptz,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("ehr_id") REFERENCES "openehr_ehr" ("ehr_id")
);

CREATE TABLE IF NOT EXISTS "openehr_version" (
  "uid" text NOT NULL,
  "versioned_object_uid" text NOT NULL,
  "creating_system_id" text NOT NULL,
  "trunk_version" bigint NOT NULL,
  "branch_number" bigint,
  "branch_version" bigint,
  "preceding_version_uid" text,
  "lifecycle_state_code" text NOT NULL,
  "is_deleted" boolean NOT NULL,
  "contribution_uid" text NOT NULL,
  "audit_system_id" text NOT NULL,
  "audit_change_type_code" text NOT NULL,
  "audit_committer_name" text,
  "audit_time_committed_text" text NOT NULL,
  "audit_time_committed_utc" timestamptz,
  "data_json" jsonb,
  "audit_description" text,
  "signature" text,
  "attestations_json" jsonb,
  "other_input_version_uids_json" jsonb,
  "chain_previous" bytea NOT NULL,
  "chain_content" bytea NOT NULL,
  "chain_digest" bytea NOT NULL,
  "chain_tag_key_id" text,
  "chain_tag_mac" bytea,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("versioned_object_uid") REFERENCES "openehr_versioned_object" ("uid")
);

CREATE TABLE IF NOT EXISTS "openehr_contribution" (
  "uid" text NOT NULL,
  "ehr_id" text NOT NULL,
  "audit_change_type_code" text NOT NULL,
  "audit_system_id" text NOT NULL,
  "audit_committer_name" text,
  "audit_time_committed_text" text NOT NULL,
  "audit_time_committed_utc" timestamptz,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("ehr_id") REFERENCES "openehr_ehr" ("ehr_id")
);

CREATE TABLE IF NOT EXISTS "openehr_composition_index" (
  "version_uid" text NOT NULL,
  "ehr_id" text NOT NULL,
  "archetype_id" text NOT NULL,
  "template_id" text,
  "category_code" text NOT NULL,
  "composer_name" text,
  "language_code" text NOT NULL,
  "territory_code" text NOT NULL,
  "setting_code" text,
  "context_start_text" text,
  "context_start_utc" timestamptz,
  "context_end_text" text,
  "context_end_utc" timestamptz,
  PRIMARY KEY ("version_uid"),
  FOREIGN KEY ("version_uid") REFERENCES "openehr_version" ("uid")
);

CREATE INDEX IF NOT EXISTS "ix_versioned_object_ehr" ON "openehr_versioned_object" ("ehr_id", "rm_type");

CREATE UNIQUE INDEX IF NOT EXISTS "ix_version_container_trunk" ON "openehr_version" ("versioned_object_uid", "trunk_version", "branch_number", "branch_version");

CREATE INDEX IF NOT EXISTS "ix_version_time" ON "openehr_version" ("versioned_object_uid", "audit_time_committed_utc");

CREATE INDEX IF NOT EXISTS "ix_version_preceding" ON "openehr_version" ("preceding_version_uid");

CREATE INDEX IF NOT EXISTS "ix_contribution_ehr_time" ON "openehr_contribution" ("ehr_id", "audit_time_committed_utc");

CREATE INDEX IF NOT EXISTS "ix_composition_archetype" ON "openehr_composition_index" ("ehr_id", "archetype_id");

CREATE INDEX IF NOT EXISTS "ix_composition_context_start" ON "openehr_composition_index" ("ehr_id", "context_start_utc");

CREATE OR REPLACE FUNCTION "openehr_refuse_mutation_openehr_version"() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'openehr_version is append-only (openEHR V8.10)';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER "trg_append_only_openehr_version" BEFORE UPDATE OR DELETE ON "openehr_version" FOR EACH ROW EXECUTE FUNCTION "openehr_refuse_mutation_openehr_version"();

CREATE OR REPLACE FUNCTION "openehr_refuse_mutation_openehr_contribution"() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'openehr_contribution is append-only (openEHR V8.10)';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER "trg_append_only_openehr_contribution" BEFORE UPDATE OR DELETE ON "openehr_contribution" FOR EACH ROW EXECUTE FUNCTION "openehr_refuse_mutation_openehr_contribution"();
