-- openEHR schema for SQLite
--
-- GENERATED by `openehr-assets`. Do not edit; run `cargo run -- write`
-- in openehr-assets/ and commit the diff.
--
-- Committed so that a change to the schema or to a dialect is visible
-- as a diff at review time, and so that two dialects becoming the same
-- thing shows up as two identical files (spec/audit.md W-01).

CREATE TABLE IF NOT EXISTS "openehr_ehr" (
  "ehr_id" TEXT NOT NULL,
  "system_id" TEXT NOT NULL,
  "time_created_text" TEXT NOT NULL,
  "time_created_utc" INTEGER,
  "ehr_status_uid" TEXT NOT NULL,
  "ehr_access_uid" TEXT NOT NULL,
  PRIMARY KEY ("ehr_id")
);

CREATE TABLE IF NOT EXISTS "openehr_versioned_object" (
  "uid" TEXT NOT NULL,
  "ehr_id" TEXT NOT NULL,
  "rm_type" TEXT NOT NULL,
  "time_created_text" TEXT NOT NULL,
  "time_created_utc" INTEGER,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("ehr_id") REFERENCES "openehr_ehr" ("ehr_id")
);

CREATE TABLE IF NOT EXISTS "openehr_version" (
  "uid" TEXT NOT NULL,
  "versioned_object_uid" TEXT NOT NULL,
  "creating_system_id" TEXT NOT NULL,
  "trunk_version" INTEGER NOT NULL,
  "branch_number" INTEGER,
  "branch_version" INTEGER,
  "preceding_version_uid" TEXT,
  "lifecycle_state_code" TEXT NOT NULL,
  "is_deleted" INTEGER NOT NULL,
  "contribution_uid" TEXT NOT NULL,
  "audit_system_id" TEXT NOT NULL,
  "audit_change_type_code" TEXT NOT NULL,
  "audit_committer_name" TEXT,
  "audit_time_committed_text" TEXT NOT NULL,
  "audit_time_committed_utc" INTEGER,
  "data_json" TEXT,
  "audit_description" TEXT,
  "signature" TEXT,
  "attestations_json" TEXT,
  "other_input_version_uids_json" TEXT,
  "chain_previous" BLOB NOT NULL,
  "chain_content" BLOB NOT NULL,
  "chain_digest" BLOB NOT NULL,
  "chain_tag_key_id" TEXT,
  "chain_tag_mac" BLOB,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("versioned_object_uid") REFERENCES "openehr_versioned_object" ("uid")
);

CREATE TABLE IF NOT EXISTS "openehr_contribution" (
  "uid" TEXT NOT NULL,
  "ehr_id" TEXT NOT NULL,
  "audit_change_type_code" TEXT NOT NULL,
  "audit_system_id" TEXT NOT NULL,
  "audit_committer_name" TEXT,
  "audit_time_committed_text" TEXT NOT NULL,
  "audit_time_committed_utc" INTEGER,
  PRIMARY KEY ("uid"),
  FOREIGN KEY ("ehr_id") REFERENCES "openehr_ehr" ("ehr_id")
);

CREATE TABLE IF NOT EXISTS "openehr_composition_index" (
  "version_uid" TEXT NOT NULL,
  "ehr_id" TEXT NOT NULL,
  "archetype_id" TEXT NOT NULL,
  "template_id" TEXT,
  "category_code" TEXT NOT NULL,
  "composer_name" TEXT,
  "language_code" TEXT NOT NULL,
  "territory_code" TEXT NOT NULL,
  "setting_code" TEXT,
  "context_start_text" TEXT,
  "context_start_utc" INTEGER,
  "context_end_text" TEXT,
  "context_end_utc" INTEGER,
  PRIMARY KEY ("version_uid"),
  FOREIGN KEY ("version_uid") REFERENCES "openehr_version" ("uid")
);

CREATE INDEX IF NOT EXISTS "ix_versioned_object_ehr" ON "openehr_versioned_object" ("ehr_id", "rm_type");

CREATE UNIQUE INDEX IF NOT EXISTS "ix_version_container_trunk" ON "openehr_version" ("versioned_object_uid", "trunk_version", "branch_number", "branch_version");

CREATE INDEX IF NOT EXISTS "ix_version_time" ON "openehr_version" ("versioned_object_uid", "audit_time_committed_utc");

CREATE INDEX IF NOT EXISTS "ix_version_preceding" ON "openehr_version" ("preceding_version_uid");

CREATE INDEX IF NOT EXISTS "ix_contribution_ehr_time" ON "openehr_contribution" ("ehr_id", "audit_time_committed_utc");

CREATE INDEX IF NOT EXISTS "ix_composition_archetype" ON "openehr_composition_index" ("ehr_id", "archetype_id");

CREATE INDEX IF NOT EXISTS "ix_composition_context_start" ON "openehr_composition_index" ("ehr_id", "context_start_utc");

CREATE TRIGGER IF NOT EXISTS "trg_openehr_version_no_update" BEFORE UPDATE ON "openehr_version" BEGIN SELECT RAISE(ABORT, 'openehr_version is append-only (openEHR V8.10)'); END;

CREATE TRIGGER IF NOT EXISTS "trg_openehr_version_no_delete" BEFORE DELETE ON "openehr_version" BEGIN SELECT RAISE(ABORT, 'openehr_version is append-only (openEHR V8.10)'); END;

CREATE TRIGGER IF NOT EXISTS "trg_openehr_contribution_no_update" BEFORE UPDATE ON "openehr_contribution" BEGIN SELECT RAISE(ABORT, 'openehr_contribution is append-only (openEHR V8.10)'); END;

CREATE TRIGGER IF NOT EXISTS "trg_openehr_contribution_no_delete" BEFORE DELETE ON "openehr_contribution" BEGIN SELECT RAISE(ABORT, 'openehr_contribution is append-only (openEHR V8.10)'); END;
